"""fixing relationship issues

Revision ID: b93d734cdf55
Revises: 5e2eabaa9344
Create Date: 2025-01-21 12:31:22.289411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93d734cdf55'
down_revision = '5e2eabaa9344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agency_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_services_agency_id', 'agency', ['agency_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('agency_id')

    # ### end Alembic commands ###
