"""updated Evnet model to match form

Revision ID: 4015433658e0
Revises: 6d88b0812b87
Create Date: 2025-01-30 20:48:34.788253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4015433658e0'
down_revision = '6d88b0812b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('event', 'portfolio', 'community', 'data', 'influencer', 'celebrity', name='event_type'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('event', 'portfolio', 'community', 'data', 'influencer', 'celebrity', name='event_type'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###
