"""fixing issues

Revision ID: 73ce2d9b2130
Revises: 4597d83975f1
Create Date: 2025-01-21 20:37:06.269679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ce2d9b2130'
down_revision = '4597d83975f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_role', sa.Enum('admin', 'user'), nullable=False))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=5), nullable=False))
        batch_op.drop_column('user_role')

    # ### end Alembic commands ###
