"""added type to the notifications model

Revision ID: 53324eca26f8
Revises: df0647ab7c4c
Create Date: 2025-02-19 12:25:07.029526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53324eca26f8'
down_revision = 'df0647ab7c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
