"""Remove enum constraint from event_type

Revision ID: 57de7c89fc92
Revises: b2124a77ecae
Create Date: 2025-02-10 12:55:04.624848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57de7c89fc92'
down_revision = 'b2124a77ecae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events') as batch_op:
        batch_op.alter_column('type',
                existing_type=sa.Enum('community', 'data', 'influencer', name='event_types'),
                type_=sa.String(50),
                existing_nullable=False)
        batch_op.alter_column('event_type',
                existing_type=sa.Enum('event', 'service', name='event_types'),
                type_=sa.String(50),
                existing_nullable=True)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events') as batch_op:
        batch_op.alter_column('type',
                type_=sa.Enum('community', 'data', 'influencer', name='event_types'),
                existing_type=sa.String(50),
                existing_nullable=False)
        batch_op.alter_column('event_type',
                type_=sa.Enum('event', 'service', name='event_types'),
                existing_type=sa.String(50),
                existing_nullable=True)

    # ### end Alembic commands ###
