"""Updated Contact model

Revision ID: 7cbaae28cc75
Revises: 1b2f41ce09f9
Create Date: 2025-02-03 10:38:23.855808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbaae28cc75'
down_revision = '1b2f41ce09f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_reply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('replied_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('replied_by', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_replied_by_users', 'users', ['replied_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('replied_by')
        batch_op.drop_column('replied_at')
        batch_op.drop_column('admin_reply')

    # ### end Alembic commands ###
