"""made changes to event model

Revision ID: 951814365b60
Revises: 7cbaae28cc75
Create Date: 2025-02-07 10:54:29.738308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951814365b60'
down_revision = '7cbaae28cc75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('event_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('event', 'service', name='event_type'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('event', 'service', name='event_type'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('event_type')
        batch_op.drop_column('service_type')

    # ### end Alembic commands ###
