"""Added updated to user,contact and event models

Revision ID: b2124a77ecae
Revises: 951814365b60
Create Date: 2025-02-08 11:21:17.528561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2124a77ecae'
down_revision = '951814365b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_created_by_users', 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key('fk_event_id_events', 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_submissions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_created_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_event_id_events', type_='foreignkey')
        batch_op.drop_column('event_id')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
