"""updated the messages model

Revision ID: c4bc43fbc94e
Revises: 8e7e4d53b078
Create Date: 2025-02-13 09:14:10.019337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4bc43fbc94e'
down_revision = '8e7e4d53b078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('thread_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_admin_message', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_messages_parent_id', 'messages', ['parent_id'], ['id'])
        batch_op.create_foreign_key('fk_messages_thread_id', 'messages', ['thread_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_parent_id', type_='foreignkey')
        batch_op.drop_constraint('fk_messages_thread_id', type_='foreignkey')
        batch_op.drop_column('is_admin_message')
        batch_op.drop_column('thread_id')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
