"""updated the messages messages model

Revision ID: df0647ab7c4c
Revises: c4bc43fbc94e
Create Date: 2025-02-14 10:38:16.675308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0647ab7c4c'
down_revision = 'c4bc43fbc94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_messages_recipient_id', 'users', ['recipient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_recipient_id', type_='foreignkey')
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###
